// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: proto/control.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SentinelControl_ListServices_FullMethodName  = "/sentinel.control.v1.SentinelControl/ListServices"
	SentinelControl_GetService_FullMethodName    = "/sentinel.control.v1.SentinelControl/GetService"
	SentinelControl_AddBackend_FullMethodName    = "/sentinel.control.v1.SentinelControl/AddBackend"
	SentinelControl_RemoveBackend_FullMethodName = "/sentinel.control.v1.SentinelControl/RemoveBackend"
	SentinelControl_ListRoutes_FullMethodName    = "/sentinel.control.v1.SentinelControl/ListRoutes"
	SentinelControl_AddRoute_FullMethodName      = "/sentinel.control.v1.SentinelControl/AddRoute"
	SentinelControl_RemoveRoute_FullMethodName   = "/sentinel.control.v1.SentinelControl/RemoveRoute"
	SentinelControl_StreamConfig_FullMethodName  = "/sentinel.control.v1.SentinelControl/StreamConfig"
)

// SentinelControlClient is the client API for SentinelControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SentinelControlClient interface {
	ListServices(ctx context.Context, in *ListServicesRequest, opts ...grpc.CallOption) (*ListServicesResponse, error)
	GetService(ctx context.Context, in *GetServiceRequest, opts ...grpc.CallOption) (*GetServiceResponse, error)
	AddBackend(ctx context.Context, in *AddBackendRequest, opts ...grpc.CallOption) (*AddBackendResponse, error)
	RemoveBackend(ctx context.Context, in *RemoveBackendRequest, opts ...grpc.CallOption) (*RemoveBackendResponse, error)
	ListRoutes(ctx context.Context, in *ListRoutesRequest, opts ...grpc.CallOption) (*ListRoutesResponse, error)
	AddRoute(ctx context.Context, in *AddRouteRequest, opts ...grpc.CallOption) (*AddRouteResponse, error)
	RemoveRoute(ctx context.Context, in *RemoveRouteRequest, opts ...grpc.CallOption) (*RemoveRouteResponse, error)
	StreamConfig(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ConfigRequest, ConfigResponse], error)
}

type sentinelControlClient struct {
	cc grpc.ClientConnInterface
}

func NewSentinelControlClient(cc grpc.ClientConnInterface) SentinelControlClient {
	return &sentinelControlClient{cc}
}

func (c *sentinelControlClient) ListServices(ctx context.Context, in *ListServicesRequest, opts ...grpc.CallOption) (*ListServicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListServicesResponse)
	err := c.cc.Invoke(ctx, SentinelControl_ListServices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sentinelControlClient) GetService(ctx context.Context, in *GetServiceRequest, opts ...grpc.CallOption) (*GetServiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetServiceResponse)
	err := c.cc.Invoke(ctx, SentinelControl_GetService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sentinelControlClient) AddBackend(ctx context.Context, in *AddBackendRequest, opts ...grpc.CallOption) (*AddBackendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddBackendResponse)
	err := c.cc.Invoke(ctx, SentinelControl_AddBackend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sentinelControlClient) RemoveBackend(ctx context.Context, in *RemoveBackendRequest, opts ...grpc.CallOption) (*RemoveBackendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveBackendResponse)
	err := c.cc.Invoke(ctx, SentinelControl_RemoveBackend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sentinelControlClient) ListRoutes(ctx context.Context, in *ListRoutesRequest, opts ...grpc.CallOption) (*ListRoutesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRoutesResponse)
	err := c.cc.Invoke(ctx, SentinelControl_ListRoutes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sentinelControlClient) AddRoute(ctx context.Context, in *AddRouteRequest, opts ...grpc.CallOption) (*AddRouteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddRouteResponse)
	err := c.cc.Invoke(ctx, SentinelControl_AddRoute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sentinelControlClient) RemoveRoute(ctx context.Context, in *RemoveRouteRequest, opts ...grpc.CallOption) (*RemoveRouteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveRouteResponse)
	err := c.cc.Invoke(ctx, SentinelControl_RemoveRoute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sentinelControlClient) StreamConfig(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ConfigRequest, ConfigResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SentinelControl_ServiceDesc.Streams[0], SentinelControl_StreamConfig_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ConfigRequest, ConfigResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SentinelControl_StreamConfigClient = grpc.BidiStreamingClient[ConfigRequest, ConfigResponse]

// SentinelControlServer is the server API for SentinelControl service.
// All implementations must embed UnimplementedSentinelControlServer
// for forward compatibility.
type SentinelControlServer interface {
	ListServices(context.Context, *ListServicesRequest) (*ListServicesResponse, error)
	GetService(context.Context, *GetServiceRequest) (*GetServiceResponse, error)
	AddBackend(context.Context, *AddBackendRequest) (*AddBackendResponse, error)
	RemoveBackend(context.Context, *RemoveBackendRequest) (*RemoveBackendResponse, error)
	ListRoutes(context.Context, *ListRoutesRequest) (*ListRoutesResponse, error)
	AddRoute(context.Context, *AddRouteRequest) (*AddRouteResponse, error)
	RemoveRoute(context.Context, *RemoveRouteRequest) (*RemoveRouteResponse, error)
	StreamConfig(grpc.BidiStreamingServer[ConfigRequest, ConfigResponse]) error
	mustEmbedUnimplementedSentinelControlServer()
}

// UnimplementedSentinelControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSentinelControlServer struct{}

func (UnimplementedSentinelControlServer) ListServices(context.Context, *ListServicesRequest) (*ListServicesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListServices not implemented")
}
func (UnimplementedSentinelControlServer) GetService(context.Context, *GetServiceRequest) (*GetServiceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetService not implemented")
}
func (UnimplementedSentinelControlServer) AddBackend(context.Context, *AddBackendRequest) (*AddBackendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddBackend not implemented")
}
func (UnimplementedSentinelControlServer) RemoveBackend(context.Context, *RemoveBackendRequest) (*RemoveBackendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveBackend not implemented")
}
func (UnimplementedSentinelControlServer) ListRoutes(context.Context, *ListRoutesRequest) (*ListRoutesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRoutes not implemented")
}
func (UnimplementedSentinelControlServer) AddRoute(context.Context, *AddRouteRequest) (*AddRouteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddRoute not implemented")
}
func (UnimplementedSentinelControlServer) RemoveRoute(context.Context, *RemoveRouteRequest) (*RemoveRouteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveRoute not implemented")
}
func (UnimplementedSentinelControlServer) StreamConfig(grpc.BidiStreamingServer[ConfigRequest, ConfigResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamConfig not implemented")
}
func (UnimplementedSentinelControlServer) mustEmbedUnimplementedSentinelControlServer() {}
func (UnimplementedSentinelControlServer) testEmbeddedByValue()                         {}

// UnsafeSentinelControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SentinelControlServer will
// result in compilation errors.
type UnsafeSentinelControlServer interface {
	mustEmbedUnimplementedSentinelControlServer()
}

func RegisterSentinelControlServer(s grpc.ServiceRegistrar, srv SentinelControlServer) {
	// If the following call panics, it indicates UnimplementedSentinelControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SentinelControl_ServiceDesc, srv)
}

func _SentinelControl_ListServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListServicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SentinelControlServer).ListServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SentinelControl_ListServices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SentinelControlServer).ListServices(ctx, req.(*ListServicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SentinelControl_GetService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SentinelControlServer).GetService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SentinelControl_GetService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SentinelControlServer).GetService(ctx, req.(*GetServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SentinelControl_AddBackend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddBackendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SentinelControlServer).AddBackend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SentinelControl_AddBackend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SentinelControlServer).AddBackend(ctx, req.(*AddBackendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SentinelControl_RemoveBackend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveBackendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SentinelControlServer).RemoveBackend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SentinelControl_RemoveBackend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SentinelControlServer).RemoveBackend(ctx, req.(*RemoveBackendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SentinelControl_ListRoutes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRoutesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SentinelControlServer).ListRoutes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SentinelControl_ListRoutes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SentinelControlServer).ListRoutes(ctx, req.(*ListRoutesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SentinelControl_AddRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SentinelControlServer).AddRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SentinelControl_AddRoute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SentinelControlServer).AddRoute(ctx, req.(*AddRouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SentinelControl_RemoveRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveRouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SentinelControlServer).RemoveRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SentinelControl_RemoveRoute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SentinelControlServer).RemoveRoute(ctx, req.(*RemoveRouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SentinelControl_StreamConfig_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SentinelControlServer).StreamConfig(&grpc.GenericServerStream[ConfigRequest, ConfigResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SentinelControl_StreamConfigServer = grpc.BidiStreamingServer[ConfigRequest, ConfigResponse]

// SentinelControl_ServiceDesc is the grpc.ServiceDesc for SentinelControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SentinelControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sentinel.control.v1.SentinelControl",
	HandlerType: (*SentinelControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListServices",
			Handler:    _SentinelControl_ListServices_Handler,
		},
		{
			MethodName: "GetService",
			Handler:    _SentinelControl_GetService_Handler,
		},
		{
			MethodName: "AddBackend",
			Handler:    _SentinelControl_AddBackend_Handler,
		},
		{
			MethodName: "RemoveBackend",
			Handler:    _SentinelControl_RemoveBackend_Handler,
		},
		{
			MethodName: "ListRoutes",
			Handler:    _SentinelControl_ListRoutes_Handler,
		},
		{
			MethodName: "AddRoute",
			Handler:    _SentinelControl_AddRoute_Handler,
		},
		{
			MethodName: "RemoveRoute",
			Handler:    _SentinelControl_RemoveRoute_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamConfig",
			Handler:       _SentinelControl_StreamConfig_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/control.proto",
}
